### ISSUE TITLE
Best way to map to customized vuetify components

### ISSUE THREAD

**Issue by kguelzau** [eclipsesource/jsonforms-vuetify-renderers#115]
I am searching for a _simple_ way to map to alternative vuetify components.
Basically we have customized / wrapped components for all vuetify components we need.
I would like use these instead of the orginal vuetify components.

Do you have any advice beside creating own custom renderes?

Sorry for opening an issue for this question, but i did not find another way to get advice.
Feel free to ignore/close it. :-)

**Comment by yaffol** [comment]
Off the top of my head, I can't see a means without custom renderers, or making your own build where you import your library instead of the stock Vueitfy. There may be some clever aliasing that's possible with Vite that I don't know about, but that's only a guess, or using dynamic imports in some way.

It's quite easy to fork the project and build it if you do need to do that, though you might want to wait for https://github.com/eclipsesource/jsonforms/pull/2341 to get merged in as this will move the vue-vuetify renderer set (this repo) into a package within the main json-forms monorepo.

In terms of the best place to ask this sort of question, there is also the [community forum](https://jsonforms.discourse.group/) which has a good response level and may be an easier place to ask specific use cases and share code examples etc.
