### ISSUE TITLE
Horizontal layout cols not working

### ISSUE THREAD

**Issue by davidpede** [eclipsesource/jsonforms-vuetify-renderers#67]
Upgraded to latest beta and horizontal cols have stopped working. Column widths set like this: https://github.com/eclipsesource/jsonforms-vuetify-renderers/blob/a3b1927813ef8e0cefc424e3025850ecda3cdd67/example/src/examples/horizontal-layout/uischema.json#L23 have no effect. 

Docs site demos the issue: https://jsonforms-vuetify-renderers.netlify.app/#/example/horizontal-layout 

Was working in beta-1

**Comment by kchobantonov-runbuggy** [comment]
@sdirix  this is not working since there is a cols binding at the moment that take precedence.

**Comment by sdirix** [comment]
Hmm [I see](https://github.com/eclipsesource/jsonforms-vuetify-renderers/blob/a0f72b34697f164daeade9aef8eedbf3d29b2c5d/vue2-vuetify/src/layouts/HorizontalLayoutRenderer.vue#L60-L86). 

This collides with the collapse feature. We should probably also check the `cols` of the vuetifyProps and use them except for when the breakpoint collapse takes precedence. Do you agree?

**Comment by kchobantonov** [comment]
yes we do need to do some sort of a merge since to make the jsonform responsive automatically most likely won't work out of the box or at least not the way how the end user might expect it. I was also thinking on how to make that automatically responsive but with all variants and even hiding/showing UI elements bases on the screen size it will be better I guess to leave that as options in the UI elements (json UI schema)

**Comment by sdirix** [comment]
I pushed a fix to #68

**Comment by sdirix** [comment]
Fixed with https://github.com/eclipsesource/jsonforms-vuetify-renderers/pull/68
